name: Create WordPress plugin Zip file

on:
  release:
    types: [ released, prereleased ]

jobs:
  build:
    name: Build Plugin Artifact
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Generate plugin artifact
        run: |
          mkdir -p release/wp-help-scout-docs
          rsync -rc --exclude-from="$GITHUB_WORKSPACE/.distignore" "$GITHUB_WORKSPACE/" release/daan-strip-db-dump/ --delete --delete-excluded
          cd "${GITHUB_WORKSPACE}/release" || exit
          zip -r "${GITHUB_WORKSPACE}/wp-help-scout-docs.zip" .

      - name: Upload release asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ${{github.workspace}}/wp-help-scout-docs.zip
          asset_name: wp-help-scout-docs.zip
          asset_content_type: application/zip
